[package]
name = "kass"
version = "0.1.0"
authors = ["Matthew Salazar <m@tthewsalazar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
serde = { version = "1.0", features = ["derive"] }